### ISSUE TITLE
NPM package outdated?

### ISSUE THREAD

**Issue by johncox00** [coinbase/gdax-node#133]
Heads up: When I `yarn add gdax`'d I was not able to get a websocket connection to work because that version is still dependent on ws 1.1.1. But when I `yarn add https://github.com/coinbase/gdax-node` it works since master has ws 3.0.0 per https://github.com/coinbase/gdax-node/pull/67. 

Maybe this helps somebody else out. Maybe I'm just a nube.

**Comment by KerimG** [comment]
It's not just websocket. Even the basic public data example from the documentation fails with the NPM package.

**Comment by meteorpublish** [comment]
@coinbase guys, this npm mess is a bit ridiculous. You've raised $100M in August (and [bragged about it](https://www.facebook.com/felixboehm55/posts/10209847593370055)). Yet you can't hire an intern to clean up the [duplicate npm-related issues](https://github.com/coinbase/gdax-node/issues/153#issuecomment-348691580), and set up a proper release process?

Keeping this library broken means developers make fewer trading bots, which make fewer trades than otherwise, which means your employer doesn't earn any trading fees.

I'm curious how @barmstrong feels about this.

**Comment by ryanhaney** [comment]
The async example fails if you install from NPM. Install from github and examples start to work.

**Comment by rmm5t** [comment]
@johncox00 Would you mind closing this issue in favor of consolidating the discussion under #148? There's a wider discussion going on there.
