### ISSUE TITLE
Distinguish partial fills

### ISSUE THREAD

**Issue by meteorpublish** [coinbase/gdax-node#157]
[getFills()](https://docs.gdax.com/#fills) returns fills, but how can I tell if a fill was partial or complete, if I don't pass an `order_id`?

Even if I pass an order_id, do I have to iterate through all the fills and sum up the `size`? This should be documented.

**Comment by rmm5t** [comment]
One order can have many fills. You must sum up all the fills if you want to glean how much of the original order was filled. You can do this by querying per `order_id`, or you can group the fills by `order_id` after you pull a large list of fills back from the API.

This is pretty much already documented by the definition of what a fill is and inferred via the [GDAX API Reference](https://docs.gdax.com/#fills).

**Comment by fb55** [comment]
When listing orders there is also a `filled_size` that indicates how much of the order has been completed.

**Comment by nzhammer** [comment]
Sorry to comment on an old question / issue, but I still have concerns surrounding this and would rather not open a new issue.  Following the documentation on the GDAX API:

> Orders which are no longer resting on the order book, will be marked with the done status. There is a small window between an order being done and settled. An order is settled when all of the fills have settled and the remaining holds (if any) have been removed.

From this, I drew the conclusion that by using .getOrder(orderId) and checking result.status === 'done' && order.settled === true, I would know if my limit order was completely done filling (regardless of partial or complete fill). This turned out to be wrong. On multiple occasions I have called .getOrder(orderId), checked for a 'done' status and true settle, but have only received one partial fill of two, where calling .getOrder(orderId) a few seconds later resulted in the total fill.

 I am guessing this is because my limit order filled with two partial fills and i called .getOrder(orderId) after the first part filled and before the second. The big problem here is that this leaves me in a position where I don't know if I received a partial fill and there are more fills on the way, or if that partial fill is the only fill that will happen and my order will not be completely filled.

I imagine that .getFills(orderId) will leave me in the same predicament, as it may return one fill of many partial fills on a the order if I call it at the wrong time, but it is not easy to test this.

Is this a bug? Is there any way to know with 100% certainty that the filling of my order has completed, whether it was a single complete fill, several partial fills resulting in a complete fill, or partial fills resulting in an order that was not completely filled?
