### ISSUE TITLE
authedClient.getOrders return Internal server error

### ISSUE THREAD

**Issue by Denly** [coinbase/gdax-node#261]
I run this:
`authedClient.getOrders({ status: "open" }, (err, response, data) => {
      console.log(err, data);
    });`

Got:
`null { message: 'Internal server error' }`

p.s it was requesting to Gdax Sandbox

**Comment by rmm5t** [comment]
Cannot reproduce; although, the `err` shouldn't be `null`, and that's a dupe of #208 which was fixed in #210.

Try `npm install coinbase/gdax-node` to incorporate that particular fix.

**Comment by dereksan** [comment]
I am using coinbase/gdax-node, and am getting Internal server error in sandbox environment, however live environment returns successful. Also curious, in the sandbox call that fails, response is null (I was expecting response.status to be 500). In that case err is populated with "Error: HTTP 500 Error: Internal server error"

**Comment by evantsmith** [comment]
I am having the same problem as dereksan. getOrders() is not working with the sandbox environment but it was working last week.

**Comment by Denly** [comment]
@rmm5t I was requesting to Gdax Sandbox. Maybe the production one works, just like @dereksan said.

**Comment by dereksan** [comment]
This miraculously started working successfully again on its own. I can now perform getOrders on both live and sandbox.

**Comment by Denly** [comment]
Yes, it works again!  I will close this issue.

**Comment by bouchezb** [comment]
Hi, i'm using gdax node v0.8.0 and i'm experiencing a similar issue on `getOrder()` function.

The issue is random. It can happen only once in 5 days sometimes.
I tried to add some traces and found that an internal server error can occur with an HTTP code 200 from response.

This is not the expected behaviour, according to documentation.
https://docs.pro.coinbase.com/#requests
Internal server error may return an HTTP code 500.

```
2018-07-23 19:04:41 [19706] [verbose]: 	Refreshing order d69b3c5e-e2e2-4efa-9c14-469f64479a66 status ...
2018-07-23 19:04:41 [19706] [error]: 	Internal Server Error
2018-07-23 19:04:41 [19706] [verbose]: 	Got response HTTP 200 from exchange
```

In my case, HTTP 200 is returned by `err.response.statusCode`, not `response.statusCode`.
Do i need to consider any HTTP code from `err.response` as an error in all cases or is this a real issue ?

Thanks,
Regards.
