### ISSUE TITLE
ESLint, Typings Declaration File?

### ISSUE THREAD

**Issue by condulum** [coinbase/gdax-node#65]
I am happy to write a typescript typings declaration file for the project.

Also I suggest using AirBnB's eslint file.

**Comment by fb55** [comment]
We're currently reworking how this library works, let's wait for that to happen before adding typings. Thanks a lot for the offer though, I'll definitely come back to it!

Part of that change will be to use prettier for formatting the code, which will already take care of a lot of the advantages of airbnb's config. I'd prefer to maintain the remaining settings in this repo (it won't be that many anyway).

**Comment by kiwileaks78** [comment]
Having typings would be awesome !

**Comment by awitherow** [comment]
There is already a pretty large conversion of the codebase to a newer flavor of es6... adding type support would either need to be done by https://flow.org or typescript.

Flow would be the easiest to begin implementing, while typescript would require another rewrite... not sure if that would be desirable.

When minimally implemented (as needed, in effective areas), flowtype can be really beautiful. Otherwise it can turn your codebase into a monster you never want to touch again.

**Comment by ColtonProvias** [comment]
I'm actually finding myself in the position of rewriting this to TypeScript right now. When I'm done or close to it, I'll throw it up on GitHub.

**Comment by JakeRad** [comment]
@ColtonProvias @kiwileaks78  @condulum I've started a fork with a typings ... feel free to help out!

Pull Request:
https://github.com/coinbase/gdax-node/pull/108

Fork:
https://github.com/JakeRad/gdax-node

npm install command:
npm install github:JakeRad/gdax-node

**Comment by fb55** [comment]
Merged it! :D
